stages:
  - trigger-website-build

trigger:build-website:
  stage: trigger-website-build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - versions.json
  trigger:
    project: Northern.tech/CFEngine/build-website
    branch: production
