"""Bump the version and commit of a single module in cfbs.json.

Everything else -- versions.json, the tarballs and their checksums -- is
generated by scripts/s3uploading.js once the bump is merged to master.
"""

import argparse
import os
import re
import subprocess

from cfbs.pretty import pretty
from cfbs.utils import read_json, save_file

VERSION_REGEX = r"^(\d+)\.(\d+)\.(\d+)(-\d+)?$"


def main():
    parser = argparse.ArgumentParser(description="Bump a module in the index")
    parser.add_argument("module", help="name of the module to bump")
    parser.add_argument(
        "increment",
        choices=["major", "minor", "patch", "release"],
        help="part of the version to bump",
    )
    args = parser.parse_args()

    bump(args.module, args.increment)


def bump(name, increment):
    index = read_json("cfbs.json")
    modules = index["index"]

    assert name in modules, f"No module named '{name}' in the index"
    module = modules[name]

    while "alias" in module:
        print(f"'{name}' is an alias for '{module['alias']}'")
        name = module["alias"]
        module = modules[name]

    old_version = module["version"]
    new_version = increment_version(old_version, increment)

    versions = read_json("versions.json")
    # An already released version is silently skipped by the mirroring action
    assert (
        new_version not in versions.get(name, {})
    ), f"{name} {new_version} is already released (present in versions.json)"

    commit = resolve_commit(module["repo"])
    assert commit != module["commit"], (
        f"Commit {commit} is already in the index; "
        "'version' and 'commit' must change together"
    )

    module["version"] = new_version
    module["commit"] = commit
    # Some modules also carry their version in a build step, e.g. masterfiles'
    # "run EXPLICIT_VERSION=<version> ..."
    module["steps"] = [
        re.sub(rf"(?<![\w.-]){re.escape(old_version)}(?![\w.-])", new_version, step)
        for step in module["steps"]
    ]

    # pretty() is what `cfbs pretty` uses, which CI checks the index against
    save_file("cfbs.json", pretty(index) + "\n")

    message = f"Bumped module '{name}' from version {old_version} to {new_version}"
    print(message)

    # Let a workflow pick the message up
    if "GITHUB_OUTPUT" in os.environ:
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"commit_message={message}\n")


def increment_version(version, increment):
    match = re.match(VERSION_REGEX, version)
    assert match, f"Cannot parse current version '{version}'"
    major, minor, patch = (int(n) for n in match.group(1, 2, 3))

    # Bumping the release keeps the version itself, everything else drops the
    # release suffix since it belongs to the old version
    if increment == "release":
        release = int(match.group(4)[1:]) if match.group(4) else 0
        return f"{major}.{minor}.{patch}-{release + 1}"

    if increment == "major":
        major, minor, patch = major + 1, 0, 0
    elif increment == "minor":
        minor, patch = minor + 1, 0
    else:
        patch += 1

    return f"{major}.{minor}.{patch}"


def resolve_commit(repo):
    """Return the commit at the tip of the repository's default branch."""
    # GIT_TERMINAL_PROMPT=0 stops git from prompting for credentials on a
    # private or non-existing repository, same as in s3uploading.js
    env = dict(os.environ, GIT_TERMINAL_PROMPT="0")
    output = subprocess.check_output(
        ["git", "ls-remote", repo, "HEAD"], env=env, text=True
    )
    assert output, f"Could not resolve HEAD of {repo}"

    return output.split()[0]


if __name__ == "__main__":
    main()
